= AMQP Gravitee Policy

ifdef::env-github[]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

*Build*

`mvn clean install`

`gravitee-policy-amqp-<VERSION>.zip` will be generated in a `/targer` folder.

*Install*

Copy `gravitee-policy-amqp-<VERSION>.zip` to the `/plugins` folder on `gravitee-gateway` and `graviteeio-management-api`

*Use*

The plugin was tested with rabbitmq_server-3.7.14 with AMQP 1.0 protocol version. Run these command from `sbin` RabbitMQ installation folder of to enable AMQP 1.0 support:

`rabbitmq-plugins enable rabbitmq_amqp1_0`

Configure AMQP policy from the API management portal and specify Host, Port, Queue name, Username and password of RabbitMQ server.

If you want to use Request - Response functionality, enable corresponding checkbox. `AmqpListener` test class is provided to simulate a Echo-like response.

*TODO*

- Fix unit test for the Request-Response functionality - use separate threads
- Mock `AmqpClient` instead of `AmqpConnectionManager` There were some troubles with mocking Amqp Classes - solved now using `withoutAnnotations()` method.
- Test with other MQs
- Investigate problem with default connection.createAnonymousSender and connection.createDynamicReceiver in RabbitMQ for avoiding named response queues.

